// =========================================
// ARKAVENA — Frontmatter Schema (Zod)
// =========================================
// ARCHITECTURE.md §8. Editors own the fields declared here and nothing else.
// Route, canonical, breadcrumb, reading time and JSON-LD identity are all
// generated by the application layer and are deliberately absent.

import { z } from "zod";
import { CONTENT_TYPES, collectionForType } from "@/config/collections";
import {
  ARTICLE_TYPES,
  BUDGET_DISCLOSURES,
  CLUSTERS,
  CONTENT_STATUSES,
  CONVERSION_GOALS,
  PRICING_MODES,
  PROJECT_STATUSES,
  SEARCH_INTENTS,
  TAGS,
} from "@/config/taxonomies";

const KEBAB = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const INTERNAL_OR_ABSOLUTE_PATH = /^\//;

const kebabString = (label: string) =>
  z
    .string()
    .min(1, { message: `${label} tidak boleh kosong` })
    .regex(KEBAB, {
      message: `${label} harus lowercase kebab-case (contoh: bangun-rumah)`,
    });

const isoDate = (label: string) =>
  z.string().regex(ISO_DATE, {
    message: `${label} harus berformat YYYY-MM-DD`,
  });

const imagePath = z
  .string()
  .regex(INTERNAL_OR_ABSOLUTE_PATH, {
    message: "Path gambar harus diawali '/' (relatif terhadap /public)",
  })
  .regex(/\.(webp|avif|jpg|jpeg|png|svg)$/i, {
    message: "Gambar harus berekstensi webp, avif, jpg, jpeg, png, atau svg",
  });

export const heroSchema = z.object({
  eyebrow: z.string().min(1),
  heading: z.string().min(1),
  summary: z.string().min(1),
  image: imagePath,
  imageAlt: z.string().min(10, {
    message: "Alt text wajib deskriptif (minimal 10 karakter)",
  }),
});

export const relationshipsSchema = z.object({
  services: z.array(z.string()).default([]),
  sectors: z.array(z.string()).default([]),
  locations: z.array(z.string()).default([]),
  guides: z.array(z.string()).default([]),
  projects: z.array(z.string()).default([]),
  pinnedRelated: z.array(z.string()).default([]),
  excludedRelated: z.array(z.string()).default([]),
});

export const ctaSchema = z.object({
  label: z.string().min(1),
  href: z.string().regex(INTERNAL_OR_ABSOLUTE_PATH, {
    message: "CTA href harus berupa path internal yang diawali '/'",
  }),
  whatsappMessage: z.string().nullable().default(null),
});

export const conversionSchema = z.object({
  goal: z.enum(CONVERSION_GOALS),
  primaryCta: ctaSchema,
  secondaryCta: ctaSchema.nullable().default(null),
});

export const faqItemSchema = z.object({
  question: z.string().min(1),
  answer: z.string().min(1),
});

export const sourceSchema = z.object({
  label: z.string().min(1),
  url: z.string().url({ message: "Sumber harus berupa URL absolut" }),
  publisher: z.string().nullable().default(null),
  accessedAt: isoDate("sources[].accessedAt").nullable().default(null),
});

export const baseFrontmatterSchema = z.object({
  schemaVersion: z.literal(1),
  id: z
    .string()
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, {
      message: "id harus lowercase kebab-case dan memakai prefix koleksi",
    }),
  type: z.enum(CONTENT_TYPES),
  status: z.enum(CONTENT_STATUSES),

  title: z.string().min(1).max(120),
  slug: kebabString("slug"),
  description: z
    .string()
    .min(50, { message: "description minimal 50 karakter" })
    .max(180, { message: "description maksimal 180 karakter" }),
  excerpt: z.string().min(1),

  seoTitle: z.string().max(70).nullable().default(null),
  primaryKeyword: z.string().min(1).nullable().default(null),
  secondaryKeywords: z.array(z.string()).default([]),
  searchIntent: z.enum(SEARCH_INTENTS),

  cluster: z.enum(CLUSTERS),
  tags: z
    .array(z.enum(TAGS))
    .min(2, { message: "Minimal dua controlled tag per halaman" }),

  publishedAt: isoDate("publishedAt").nullable().default(null),
  updatedAt: isoDate("updatedAt").nullable().default(null),
  lastReviewedAt: isoDate("lastReviewedAt").nullable().default(null),
  author: z.string().min(1),
  reviewedBy: z.string().nullable().default(null),

  hero: heroSchema,
  relationships: relationshipsSchema,
  conversion: conversionSchema,

  faq: z.array(faqItemSchema).default([]),
  sources: z.array(sourceSchema).default([]),
  ownerVerified: z.boolean(),
});

// -----------------------------------------
// Collection extensions (ARCHITECTURE.md §8.4)
// -----------------------------------------

export const serviceExtension = z.object({
  serviceType: z.string().min(1),
  audience: z.array(z.string()).default([]),
  deliverables: z.array(z.string()).default([]),
  areaServed: z.array(z.string()).default([]),
  pricingMode: z.enum(PRICING_MODES),
});

export const sectorExtension = z.object({
  buildingType: z.string().min(1),
  primaryUseCases: z.array(z.string()).default([]),
  commonRisks: z.array(z.string()).default([]),
  relevantServices: z.array(z.string()).default([]),
});

export const locationExtension = z.object({
  city: z.string().min(1),
  province: z.string().min(1),
  country: z.string().min(1),
  areaServedLabel: z.string().min(1),
  localChallenges: z.array(z.string()).default([]),
  logisticsNotes: z.array(z.string()).default([]),
  localProjectRefs: z.array(z.string()).default([]),
  localFactsVerified: z.boolean(),
});

export const articleExtension = z.object({
  articleType: z.enum(ARTICLE_TYPES),
  pillar: z.string().nullable().default(null),
  dataAsOf: isoDate("article.dataAsOf").nullable().default(null),
  answerFirst: z.boolean().default(true),
  hasCalculator: z.boolean().default(false),
});

export const projectExtension = z.object({
  projectName: z.string().min(1),
  disclosureName: z.string().min(1),
  location: z.string().min(1),
  sector: z.string().nullable().default(null),
  services: z.array(z.string()).default([]),
  year: z.number().int().min(1900).max(2100).nullable().default(null),
  status: z.enum(PROJECT_STATUSES),
  areaM2: z.number().positive().nullable().default(null),
  budgetDisclosure: z.enum(BUDGET_DISCLOSURES),
  clientPermission: z.boolean(),
  factsVerified: z.boolean(),
  outcomes: z.array(z.string()).default([]),
});

export const landingExtension = z.object({
  campaign: z.string().min(1),
  organicEquivalent: z.string().nullable().default(null),
  index: z.literal(false),
  follow: z.boolean().default(true),
  showGlobalNavigation: z.boolean().default(false),
  thankYouPath: z.string().regex(INTERNAL_OR_ABSOLUTE_PATH),
});

// -----------------------------------------
// Discriminated union
// -----------------------------------------

const pageFrontmatter = baseFrontmatterSchema.extend({
  type: z.literal("page"),
});
const serviceFrontmatter = baseFrontmatterSchema.extend({
  type: z.literal("service"),
  service: serviceExtension,
});
const sectorFrontmatter = baseFrontmatterSchema.extend({
  type: z.literal("sector"),
  sector: sectorExtension,
});
const locationFrontmatter = baseFrontmatterSchema.extend({
  type: z.literal("location"),
  location: locationExtension,
});
const guideFrontmatter = baseFrontmatterSchema.extend({
  type: z.literal("guide"),
  article: articleExtension,
});
const projectFrontmatter = baseFrontmatterSchema.extend({
  type: z.literal("project"),
  project: projectExtension,
});
const landingFrontmatter = baseFrontmatterSchema.extend({
  type: z.literal("landing"),
  landing: landingExtension,
});

const frontmatterUnion = z.discriminatedUnion("type", [
  pageFrontmatter,
  serviceFrontmatter,
  sectorFrontmatter,
  locationFrontmatter,
  guideFrontmatter,
  projectFrontmatter,
  landingFrontmatter,
]);

/**
 * Publication gates. Draft content is allowed to be incomplete on purpose —
 * these rules only bite the moment a page claims to be published.
 * ARCHITECTURE.md §7.2 / §8.3.
 */
export const frontmatterSchema = frontmatterUnion.superRefine((data, ctx) => {
  const expectedPrefix = collectionForType(data.type).idPrefix;
  if (!data.id.startsWith(expectedPrefix)) {
    ctx.addIssue({
      code: "custom",
      path: ["id"],
      message: `id untuk type "${data.type}" harus diawali "${expectedPrefix}"`,
    });
  }

  if (data.status !== "published") return;

  if (!data.ownerVerified) {
    ctx.addIssue({
      code: "custom",
      path: ["ownerVerified"],
      message: "Halaman published wajib ownerVerified: true",
    });
  }

  if (!data.primaryKeyword) {
    ctx.addIssue({
      code: "custom",
      path: ["primaryKeyword"],
      message: "Halaman published wajib memiliki primaryKeyword",
    });
  }

  if (!data.publishedAt) {
    ctx.addIssue({
      code: "custom",
      path: ["publishedAt"],
      message: "Halaman published wajib memiliki publishedAt",
    });
  }

  if (!data.updatedAt) {
    ctx.addIssue({
      code: "custom",
      path: ["updatedAt"],
      message: "Halaman published wajib memiliki updatedAt",
    });
  }

  if (data.type === "location" && !data.location.localFactsVerified) {
    ctx.addIssue({
      code: "custom",
      path: ["location", "localFactsVerified"],
      message:
        "Halaman wilayah published wajib localFactsVerified: true — fakta lokal tidak boleh diasumsikan",
    });
  }

  if (data.type === "project") {
    if (!data.project.factsVerified) {
      ctx.addIssue({
        code: "custom",
        path: ["project", "factsVerified"],
        message: "Halaman proyek published wajib factsVerified: true",
      });
    }
    if (!data.project.clientPermission) {
      ctx.addIssue({
        code: "custom",
        path: ["project", "clientPermission"],
        message:
          "Halaman proyek published wajib clientPermission: true sebelum dipublikasikan",
      });
    }
  }

  if (data.type === "guide" && data.article.articleType === "cost") {
    if (!data.article.dataAsOf) {
      ctx.addIssue({
        code: "custom",
        path: ["article", "dataAsOf"],
        message:
          "Panduan biaya published wajib mencantumkan article.dataAsOf agar angka bisa diaudit",
      });
    }
  }
});

export type Frontmatter = z.infer<typeof frontmatterSchema>;
export type ServiceFrontmatter = z.infer<typeof serviceFrontmatter>;
export type SectorFrontmatter = z.infer<typeof sectorFrontmatter>;
export type LocationFrontmatter = z.infer<typeof locationFrontmatter>;
export type GuideFrontmatter = z.infer<typeof guideFrontmatter>;
export type ProjectFrontmatter = z.infer<typeof projectFrontmatter>;
export type LandingFrontmatter = z.infer<typeof landingFrontmatter>;
export type PageFrontmatter = z.infer<typeof pageFrontmatter>;
