/**
 * Regenerates every derived content artifact.
 *
 * Outputs (never edit by hand):
 *   src/generated/content-manifest.generated.ts
 *   src/generated/content-modules.generated.ts
 *   src/generated/link-graph.generated.json
 */

import fs from "node:fs";
import path from "node:path";
import { COLLECTION_NAMES, CONTENT_ROOT } from "../src/config/collections";
import { loadAllContent } from "../src/lib/content/loaders";
import { buildLinkGraph } from "../src/lib/content/link-graph";

const GENERATED_DIR = path.join(process.cwd(), "src", "generated");

const BANNER = `// AUTO-GENERATED by scripts/generate-content-manifest.ts — DO NOT EDIT.
// Run \`npm run content:manifest\` after changing anything under /content.
`;

function ensureContentDirs() {
  for (const collection of COLLECTION_NAMES) {
    const dir = path.join(process.cwd(), CONTENT_ROOT, collection);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  }
}

function writeManifest(items: ReturnType<typeof loadAllContent>["items"]) {
  const file = path.join(GENERATED_DIR, "content-manifest.generated.ts");
  const body = `${BANNER}
import type { ContentItem } from "@/schemas/content-types";

export const contentManifest: ContentItem[] = ${JSON.stringify(items, null, 2)};
`;
  fs.writeFileSync(file, body, "utf8");
  return file;
}

function writeModuleRegistry(items: ReturnType<typeof loadAllContent>["items"]) {
  const file = path.join(GENERATED_DIR, "content-modules.generated.ts");

  const entries = items
    .map((item) => {
      const key = `${item.collection}/${item.slug}`;
      const importPath = `../../${CONTENT_ROOT}/${item.collection}/${item.slug}.mdx`;
      return `  "${key}": () => import("${importPath}"),`;
    })
    .join("\n");

  const body = `${BANNER}
import type { MDXProps } from "mdx/types";
import type { JSX } from "react";

export type MdxModule = { default: (props: MDXProps) => JSX.Element };

/**
 * Explicit import map rather than a dynamic template-literal import: it keeps
 * bundling deterministic and makes every renderable MDX file auditable.
 */
export const contentModules: Record<string, () => Promise<MdxModule>> = {
${entries}
};
`;
  fs.writeFileSync(file, body, "utf8");
  return file;
}

function writeLinkGraph(items: ReturnType<typeof loadAllContent>["items"]) {
  const file = path.join(GENERATED_DIR, "link-graph.generated.json");
  const graph = buildLinkGraph(items);
  fs.writeFileSync(file, `${JSON.stringify(graph, null, 2)}\n`, "utf8");
  return file;
}

function main() {
  ensureContentDirs();
  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  const { items, issues } = loadAllContent();

  if (issues.length > 0) {
    console.error(`\n✖ Manifest generation gagal — ${issues.length} masalah frontmatter:\n`);
    for (const issue of issues) {
      console.error(`  ${issue.file}\n    ${issue.field}: ${issue.message}`);
    }
    console.error("");
    process.exit(1);
  }

  const written = [
    writeManifest(items),
    writeModuleRegistry(items),
    writeLinkGraph(items),
  ];

  console.log(`✔ Manifest dibuat dari ${items.length} file MDX.`);
  for (const file of written) {
    console.log(`  → ${path.relative(process.cwd(), file)}`);
  }
}

main();
